name: "Prepare klogg mac packages"
description: ""
inputs:
  p12-file-base64:
    required: true
  p12-password:
    required: true
  notarization-username:
    required: true
  notarization-team:
    required: true
  notarization-password:
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Mac prepare codesign
      id: prepare-codesign
      if: ${{ github.event_name != 'pull_request' }} 
      uses: apple-actions/import-codesign-certs@v1
      with: 
        p12-file-base64: ${{ inputs.p12-file-base64 }}
        p12-password: ${{ inputs.p12-password }}
     
    - name: Mac deploy Qt
      shell: sh
      run: |
        cd $KLOGG_BUILD_ROOT
        macdeployqt ./output/klogg.app -always-overwrite -verbose=2

    - name: Mac deploy Qt fixing
      if: "startsWith(matrix.config.qt_version, '5')"
      shell: sh
      run: |
        python3 $KLOGG_BUILD_ROOT/macdeployqtfix.py $KLOGG_BUILD_ROOT/output/klogg.app/Contents/MacOS/klogg $Qt5_DIR

    - name: Mac deploy Qt fixing
      if: "startsWith(matrix.config.qt_version, '6')"
      shell: sh
      run: |
        python3 $KLOGG_BUILD_ROOT/macdeployqtfix.py $KLOGG_BUILD_ROOT/output/klogg.app/Contents/MacOS/klogg $Qt6_DIR
    
    - name: Set packaging env
      shell: sh
      run: |
        echo "KLOGG_CODESIGN=Developer ID Application: Anton Filimonov (GAW773U324)" >> $GITHUB_ENV
        echo "KLOGG_INSTALLERSIGN=Developer ID Installer: Anton Filimonov (GAW773U324)" >> $GITHUB_ENV
        echo "KLOGG_DMG=klogg-${{ env.KLOGG_VERSION }}-OSX-${{ env.KLOGG_QT }}.dmg" >> $GITHUB_ENV
        echo "KLOGG_PKG=klogg-${{ env.KLOGG_VERSION }}-OSX-${{ env.KLOGG_QT }}.pkg" >> $GITHUB_ENV

    - name: Mac codesign binaries
      if: ${{ github.event_name != 'pull_request' }}
      shell: sh
      run: |
        cd $KLOGG_BUILD_ROOT
        codesign -v -f -o runtime --deep --timestamp -s "${{ env.KLOGG_CODESIGN }}" ./output/klogg.app;
    
    - name: Mac pack dmg
      shell: sh
      run: |
        cd $KLOGG_BUILD_ROOT
        cpack --verbose -G "DragNDrop"

    - name: Mac codesign dmg
      if: ${{ github.event_name != 'pull_request' }}
      shell: sh
      run: |
        cd $KLOGG_BUILD_ROOT
        mv ./packages/klogg-${{ env.KLOGG_VERSION }}-OSX.dmg ./packages/${{ env.KLOGG_DMG }}
        codesign -v -f -o runtime --timestamp -s "${{ env.KLOGG_CODESIGN }}" ./packages/${{ env.KLOGG_DMG }}
    
    - name: "Mac build pkg"
      if: ${{ github.event_name != 'pull_request' }}
      shell: sh
      run: |
        cd $KLOGG_BUILD_ROOT
        mkdir -p pkg_resources/en.lproj
        cp ../COPYING pkg_resources/en.lproj
        cp ../packaging/description.txt pkg_resources/en.lproj
        sed -e s/%klogg_version%/${{ env.KLOGG_VERSION }}/ -e s/%klogg_pkg%/klogg-${{ env.KLOGG_VERSION }}-OSX.pkg/ ../packaging/osx/distribution.xml > distribution.xml
        pkgbuild --component ./output/klogg.app --install-location /Applications --version ${{ env.KLOGG_VERSION }} --sign "${{ env.KLOGG_INSTALLERSIGN }}" --timestamp ./output/klogg-${{ env.KLOGG_VERSION }}-OSX.pkg
        productbuild --package-path ./output --distribution distribution.xml --resources ./pkg_resources --sign "${{ env.KLOGG_INSTALLERSIGN }}" --timestamp ./output/klogg-${{ env.KLOGG_VERSION }}-OSX-product.pkg
        pkgutil --expand ./output/klogg-${{ env.KLOGG_VERSION }}-OSX-product.pkg ./output/klogg_product_pkg
        pkgutil --flatten ./output/klogg_product_pkg ./output/klogg-${{ env.KLOGG_VERSION }}-OSX-flatten.pkg
        productsign --sign "${{ env.KLOGG_INSTALLERSIGN }}" --timestamp ./output/klogg-${{ env.KLOGG_VERSION }}-OSX-flatten.pkg ./packages/${{ env.KLOGG_PKG }}
    
    - name: Setup Xcode
      shell: sh
      run: sudo xcode-select -s /Applications/Xcode_13.2.1.app

    - name: Mac notarize DMG 
      if: ${{ github.event_name != 'pull_request' }} 
      shell: sh
      run: |
        xcrun notarytool submit --wait --apple-id "${{ inputs.notarization-username }}" --team-id "${{ inputs.notarization-team }}" --password "${{ inputs.notarization-password }}" "${{ env.KLOGG_BUILD_ROOT }}/packages/${{ env.KLOGG_DMG }}"

    - name: Mac staple DMG 
      if: ${{ github.event_name != 'pull_request' }} 
      shell: sh
      run: |
        xcrun stapler staple "${{ env.KLOGG_BUILD_ROOT }}/packages/${{ env.KLOGG_DMG }}"

    - name: Mac notarize PKG 
      if: ${{ github.event_name != 'pull_request' }} 
      shell: sh
      run: |
        xcrun notarytool submit  --wait --apple-id "${{ inputs.notarization-username }}" --team-id "${{ inputs.notarization-team }}" --password "${{ inputs.notarization-password }}" "${{ env.KLOGG_BUILD_ROOT }}/packages/${{ env.KLOGG_PKG }}"

    - name: Mac staple PKG 
      if: ${{ github.event_name != 'pull_request' }} 
      shell: sh 
      run: |
        xcrun stapler staple "${{ env.KLOGG_BUILD_ROOT }}/packages/${{ env.KLOGG_PKG }}"

    - name: Mac symbols
      shell: sh
      run: |
        cd $KLOGG_BUILD_ROOT
        cp -a ./output/klogg.dSym ./packages/klogg-${{ env.KLOGG_QT }}.dSym
        cp -a ./output/klogg.app ./packages/klogg-${{ env.KLOGG_QT }}.app
